Create feeds
t-vinn/faceHook pull request #10
Opened 2017-02-10 04:03 UTC by t-vinn

user/feedsに投稿一覧表示と新規投稿作成機能
プロトタイプなので以下の点は要修正
- 投稿は文字のみ、字数制限などなし→validation
- そもそもuser/feedsへのリンクがない→ルートに作る？（ただルートは次のファーストビュー作成で弄ることになりそうなのでその時でも？）
- 投稿一覧表示でuser_idを表示しているがおそらくnameに変えた方が良い

2017-02-10 07:51 UTC, NaotoOta requested changes

2017-02-10 07:51 UTC, NaotoOta commented on app/controllers/users/users/feeds_controller.rb
> +          redirect_to '/users/feeds', notice: 'a new feed created'
redirect_toは`hoge_path`を使うのがセオリー

2017-02-10 07:51 UTC, NaotoOta commented on app/controllers/users/users/feeds_controller.rb
> +        if @feed.save
@にする必要ないよね

2017-02-10 07:51 UTC, NaotoOta commented on app/views/users/users/feeds/index.html.slim
> +//ここに多分フィード一覧？
多分とは

2017-02-10 07:51 UTC, NaotoOta commented on app/views/users/users/feeds/index.html.slim
> += link_to 'Back', :back
このviewのスクショがほしい

2017-02-10 07:51 UTC, NaotoOta commented on app/views/users/users/index.html.slim
> += link_to 'Feeds', 'users/feeds'
これもpath使う

2017-02-10 07:51 UTC, NaotoOta commented on app/views/users/users/feeds/index.html.slim
> += link_to 'Back', :back
:backってできるん！？？

2017-02-10 07:51 UTC, NaotoOta commented on app/views/users/users/feeds/_form.html.slim
> += form_for @feed, url: { action: 'create' } do |f|
urlいらんはず

2017-02-10 07:51 UTC, NaotoOta commented on app/views/users/users/feeds/_form.html.slim
> += form_for @feed, url: { action: 'create' } do |f|
あとpartial使うならインスタンス変数を使わない
ローカル変数を渡すようにする

2017-02-10 09:13 UTC, t-vinn commented on app/views/users/users/feeds/index.html.slim
> += link_to 'Back', :back
backはできるみたいです。ただいきなりURL叩いてこのビューに行ったりすると変なことになったりしますが、、

2017-02-10 09:14 UTC, NaotoOta commented on app/views/users/users/feeds/index.html.slim
> += link_to 'Back', :back
じゃあやめよ

2017-02-10 09:20 UTC, t-vinn commented on app/views/users/users/feeds/index.html.slim
> += link_to 'Back', :back
変になるというか例えばusers/feedsで投稿→投稿→投稿と繰り返した場合backはそのままusers/feedsに行くので、あんまり意味がないですね。とりあえずusers/users#indexに飛ばします

2017-02-10 09:47 UTC, t-vinn commented on app/views/users/users/feeds/_form.html.slim
> += form_for @feed, url: { action: 'create' } do |f|
単数形リソースはURLを指定しなきゃいけないというのは、また別の話ですか？
https://railsguides.jp/routing.html#%E5%8D%98%E6%95%B0%E5%BD%A2%E3%83%AA%E3%82%BD%E3%83%BC%E3%82%B9

2017-02-10 09:51 UTC, NaotoOta commented on app/views/users/users/feeds/_form.html.slim
> += form_for @feed, url: { action: 'create' } do |f|
別
それはcreateとかupdateとかじゃない独自のアクションに飛ばす時の話

2017-02-10 09:51 UTC, NaotoOta commented on app/views/users/users/feeds/index.html.slim
> += link_to 'Back', :back
OK

2017-02-11 10:11 UTC, NaotoOta requested changes

2017-02-11 10:11 UTC, NaotoOta commented on app/controllers/users/sessions_controller.rb
> +      @public_feeds = Feed.where(privacy: 0)
scopeにしたい&enumなら0ではなく英語の方使いたい

2017-02-11 10:11 UTC, NaotoOta commented on app/controllers/users/users/feeds_controller.rb
> +      end
こんなんできんのｗｗ

2017-02-11 10:13 UTC, t-vinn commented on app/controllers/users/users/feeds_controller.rb
> +      end
これrails5から導入されたとかいうことで、使って見ました
http://qiita.com/QUANON/items/0033a5adb76d0cb963cd

2017-02-11 10:19 UTC, t-vinn commented on app/controllers/users/sessions_controller.rb
> +      @public_feeds = Feed.where(privacy: 0)
Feed.publicみたいに取りたいってことですよね

2017-02-11 13:10 UTC, NaotoOta commented on app/models/feed.rb
> +  enum privacy: { public_feed: 0, follower_only_feed: 1, private_feed: 2 }
_feedいらんな

2017-02-11 13:10 UTC, NaotoOta commented on app/controllers/users/users/feeds_controller.rb
> +        ))
ちょっとこれわかりにくいからコメント付けといて
Feed.public.or(current_user.feeds).or(Feed.follower_only.where(user: current_user.following_users))
順番もこっちのほうがわかりやすそう

2017-02-12 02:59 UTC, t-vinn commented on app/models/feed.rb
> +  enum privacy: { public_feed: 0, follower_only_feed: 1, private_feed: 2 }
feedいらないんですが、publicがすでに予約されてしまってて（多分privateも）
_feed取るならfollower_onlyだけですが、バランスをとってみました。
他に分かりやすい英語があればいいんですが

2017-02-12 03:00 UTC, t-vinn commented on app/controllers/users/users/feeds_controller.rb
> +        ))
うーんそうですね。もっとわかりやすくしないと。。

2017-02-12 03:01 UTC, NaotoOta commented on app/models/feed.rb
> +  enum privacy: { public_feed: 0, follower_only_feed: 1, private_feed: 2 }
あーそう言えば確かに
FiNCでもshare_with_all、share_with_follower、share_with_only_me
になってたわ

2017-02-12 03:01 UTC, t-vinn commented on app/models/feed.rb
> +  enum privacy: { public_feed: 0, follower_only_feed: 1, private_feed: 2 }
なるほど。そっちのがわかりやすいですね

2017-02-12 03:16 UTC, t-vinn commented on app/controllers/users/users/feeds_controller.rb
> +        ))
.orで繋げるならstructually compatibleじゃなきゃいけないみたいです。つまりcurrent_user.feedsはFeed.whereとstructually compatibleじゃないからダメらしい

2017-02-12 03:57 UTC, t-vinn commented on app/controllers/users/users/feeds_controller.rb
> +        ))
色々試してみましたが.orを使うならFeed.~の形じゃないとダメでwhere(user: current_user)っていうあまり綺麗じゃないものになる。.or使わないとwhereでベタ書きしないといけない、と言った感じでした。

2017-02-13 08:04 UTC, merged