First view 1
t-vinn/faceHook pull request #12
Opened 2017-02-12 07:24 UTC by t-vinn

ファーストビュー１（ログイン前）
　　ログイン画面に公開feedをすべて表示
ファーストビュー２（ログイン後1)
　　users/feedsに「自分のフォローしてるユーザーの投稿（非公開のものは除く）」、「公開投稿」、「自分の投稿」の2つを表示（tab"all")
ファーストビュー３（ログイン後2、フォロワーの投稿に限定）
　　tab"following"では（自分がフォローしてないユーザーの）公開投稿や、自分の投稿は表示されなくなる

2017-02-12 07:26 UTC, t-vinn commented
cssの部分はtargetを使ったので、スクロールの手間が生じている、下のような感じ
http://codepen.io/ueokande/pen/VeRBvr

2017-02-23 01:51 UTC, t-vinn commented
css の tab切り替えの実装はinput type= radioでもでき、そっちだとスクロールはないかもしれない＝ベターな気もする。ただ 不慣れで時間かかりそうなので、一旦放置しました。

2017-02-23 02:10 UTC, t-vinn commented
問題点2: rootからusers/feeds#allにリンクを飛ばした時に#allが表示されない（遷移後に#allまたは#followingを押下すれば表示される）

2017-02-23 03:30 UTC, NaotoOta requested changes
一旦

2017-02-23 03:30 UTC, NaotoOta commented on app/assets/stylesheets/feed/feed.css
> +}
css書くならsassにしてほしい

2017-02-23 03:30 UTC, NaotoOta commented on app/controllers/users/users/feeds_controller.rb
> +          privacy: [0, 1],
0,1 じゃわからんからenumのシンボルの方使おう

2017-02-23 03:30 UTC, NaotoOta commented on app/controllers/users/users/feeds_controller.rb
> +          privacy: [0, 1],
もしくはscope作るか

2017-02-23 03:30 UTC, NaotoOta commented on app/views/users/users/feeds/index.html.slim
> += stylesheet_link_tag 'feed/feed', media: 'all'
ここに書くのは違う
cssやるのならちょい説明したほうが良いかもやな

2017-02-23 09:45 UTC, NaotoOta commented on app/assets/stylesheets/feed/feed.css
> +}
これいらんくならへん？

2017-02-23 09:46 UTC, t-vinn commented on app/assets/stylesheets/feed/feed.css
> +}
すいません、消そうと思ってたのがrubocopに気を取られて忘れてました

2017-02-23 09:46 UTC, NaotoOta commented on app/views/users/users/feeds/index.html.slim
> +script src="https://cdn.rawgit.com/twbs/bootstrap/v4-dev/dist/js/bootstrap.js"
これここじゃなくてapplication.html.slim
https://github.com/FiNCDeveloper/online_works/blob/master/app/views/layouts/admins/application.html.slim
参考

2017-02-23 10:17 UTC, t-vinn commented on app/views/users/users/feeds/index.html.slim
> +script src="https://cdn.rawgit.com/twbs/bootstrap/v4-dev/dist/js/bootstrap.js"
application.html.slimはちゃんとしてたので上の3行不要でした。消しても問題なく動きました

2017-02-24 01:35 UTC, NaotoOta requested changes
もうちょい

2017-02-24 01:35 UTC, NaotoOta commented on app/views/users/users/feeds/index.html.slim
> +ul class="nav nav-tabs"
slimでは
`ul.nav.nav-tabs`
って書くとそのプロパティにクラスがあてられる。
idは`#hoge`ね

2017-02-24 01:35 UTC, NaotoOta commented on config/initializers/assets.rb
> +Rails.application.config.assets.precompile += %w(feed/feed.css)
ここもいらんな

2017-02-24 01:38 UTC, t-vinn commented on config/initializers/assets.rb
> +Rails.application.config.assets.precompile += %w(feed/feed.css)
これセルフチェック漏れでした。失礼しました

2017-02-24 02:01 UTC, NaotoOta approved these changes

2017-02-24 02:01 UTC, merged