Feed revision
t-vinn/faceHook pull request #13
Opened 2017-02-23 07:31 UTC by t-vinn

this branch should be merged to master only after branch "first_view_1" is merged to master.

this PR contains 
- reply functions to all feeds
- editing privacy of feeds (current_user's own feeds only)

as of 2017.02.23 16:30

2017-02-24 06:01 UTC, NaotoOta requested changes
見た

2017-02-24 06:01 UTC, NaotoOta commented on app/controllers/users/users/feed_favorites_controller.rb
> +        if FeedFavorite.create!(user_id: current_user.id, feed_id: feed.id)
create! は失敗するとerrorはいてraiseするのでこれだとelseの意味がない

2017-02-24 06:01 UTC, NaotoOta commented on app/controllers/users/users/replies_controller.rb
> +      before_action :set_feed, only: [:new]
全く間違ってないんやけどOWでは可読性が下がるということであまりつかわない

2017-02-24 06:01 UTC, NaotoOta commented on app/controllers/users/users/replies_controller.rb
> +        if Reply.create!(reply_params)
create! は失敗するとerrorはいてraiseするのでこれだとelseの意味がない

2017-02-24 06:01 UTC, NaotoOta commented on app/views/users/users/feeds/edit.html.slim
> +  div class='field'
class

2017-02-24 06:01 UTC, NaotoOta commented on app/views/users/users/feeds/edit.html.slim
> +  div class='actions'
class

2017-02-24 06:01 UTC, NaotoOta commented on app/views/users/users/feeds/edit.html.slim
> +  div class='field'
divにかんしては
ただの`.field`でいける

2017-02-24 06:01 UTC, NaotoOta commented on app/views/users/users/feeds/index.html.slim
> +          th colspan ='1'
colspan=1の時はなにも書かなくていいよ

2017-02-24 06:01 UTC, NaotoOta commented on app/views/users/users/feeds/index.html.slim
> +               = link_to 'Favorite', users_feed_feed_favorites_path(feed),
ここはtdわけない理由は？

2017-02-24 06:01 UTC, NaotoOta commented on app/views/users/users/replies/new.html.slim
> +  div class ='field'
classね

2017-02-24 06:03 UTC, t-vinn commented on app/views/users/users/feeds/index.html.slim
> +               = link_to 'Favorite', users_feed_feed_favorites_path(feed),
公開度の編集は自分の書いたfeedのみに対してできる
ファボは他人のfeedに対してのみできる
ということでどっちかしかないので、空欄だらけが2行できるよりは一行にまとめた方が見やすいかと思って

2017-02-24 06:11 UTC, t-vinn commented on app/controllers/users/users/feed_favorites_controller.rb
> +        if FeedFavorite.create!(user_id: current_user.id, feed_id: feed.id)
確かにそうでした。error出てきた画面のメッセとかUIとしてはわかりにくいのでcreate!の!をなくしてelseつけます

2017-02-27 06:58 UTC, NaotoOta reviewed
一個だけ

2017-02-27 06:58 UTC, NaotoOta commented on app/controllers/users/users/feed_favorites_controller.rb
> +        feed_favorite = FeedFavorite.new(user_id: current_user.id, feed_id: params[:feed_id])
`current_user.build_feed_favarites(feed_id: params[:feed_id])`のほうがきれい？

2017-02-27 06:59 UTC, NaotoOta commented
@t-vinn 動作確認は済んでるよね？

2017-02-27 07:39 UTC, NaotoOta approved these changes

2017-02-27 07:39 UTC, merged