Group
t-vinn/faceHook pull request #16
Opened 2017-02-27 11:41 UTC by t-vinn

できること
- グループ作成
    - 作成時に作成者の相互フォローユーザーをメンバー登録できる
- グループへのメンバー招待
- 投稿
    - 投稿へのいいね

2017-02-27 13:04 UTC, NaotoOta requested changes
一旦

2017-02-27 13:04 UTC, NaotoOta commented on config/routes.rb
> +    resources :groups, except: [:new, :destroy], module: :users do
あれ、やっぱりこのroutingならcontrollerのnest一個多くない？
あーなるほど
これmoduleいらんぞ
followで指摘しとけばよかったな

2017-02-28 00:59 UTC, t-vinn commented on config/routes.rb
> +    resources :groups, except: [:new, :destroy], module: :users do
followの時はmoduleとnamespaceで生成されるURLとControllerの違いで混乱してmoduleを使う（moduleを使ってcontrollerのネストを増やす）際の気持ちがつかめず、そのままなんとなくつけてました。
自分なりには、
moduleつけてないのはdevise系のuser認証系
で、それ以外はmoduleをつけているから整合性はあるのかなと思ってました。

2017-02-28 01:23 UTC, NaotoOta commented on config/routes.rb
> +    resources :groups, except: [:new, :destroy], module: :users do
違う
module使うのは基本的にresourcesの中にresources書くとき

2017-02-28 01:36 UTC, t-vinn commented on config/routes.rb
> +    resources :groups, except: [:new, :destroy], module: :users do
なるほど。
つまり、resourcesをネストしたのでURLはネストできたけど、コントローラーがネストしてないからネストしよう、って時にmoduleつけるということですか。
それに従うとnamespace直下のresources(follow_relationshipsやgroupsなど）にはmodule:users不要で、その下にmoduleつける。つまり例えばgroupなら
resources :groups do
  resources :groups_users, module: :groups
  resources :group_posts, module: :groups do
    resources :group_post_favorites
  end
end
みたいすれば良いでしょうか

2017-02-28 16:41 UTC, t-vinn commented
route変更に伴うcontrollerとviewのパス変更は終わりました。ただ、コントローラーどれもBaseControllerを継承させてて、これでも動きはしますがBaseControllerじゃなくてRepliesControllerとかを継承させた方が良い気がします。
このBaseControllerらへんをいじってしまうと元に戻すのが一苦労なので、一応ここで確認させてもらっても良いでしょうか。

2017-03-02 02:28 UTC, NaotoOta requested changes
一旦

2017-03-02 02:28 UTC, NaotoOta commented on app/controllers/users/feeds/feed_favorites_controller.rb
> +  module Feeds
これは何？？

2017-03-02 02:28 UTC, NaotoOta commented on config/routes.rb
> +      resources :feed_favorites, only: [:create, :destroy], module: :feeds
なんでこの辺module追加する必要あるん？

2017-03-02 02:31 UTC, t-vinn commented on config/routes.rb
> +      resources :feed_favorites, only: [:create, :destroy], module: :feeds
resourcesネストしてるからつけた方がいいかと思ってましたが。

2017-03-02 02:39 UTC, NaotoOta commented on config/routes.rb
> +      resources :feed_favorites, only: [:create, :destroy], module: :feeds
あ、してた
すまん笑

2017-03-02 03:10 UTC, NaotoOta approved these changes

2017-03-02 03:11 UTC, merged