Recommend
t-vinn/faceHook pull request #25
Opened 2017-03-15 04:55 UTC by t-vinn

ロジックは、cos類似度
つまりユーザーAとBの類似度を計算しようと思ったら残りのユーザーC~Jについて
AがCをフォローしてたら1、してなかったら0
みたいな感じで
A = [1, 0, 0, 0, 0, 1, 1, 0] (AはCHIをフォロー）
B = [0, 1, 1, 0, 0, 0, 1, 1] (BはDEIJをフォロー）
と配列（ベクトル）を作って、このベクトルのなす角のcos(0~1)が類似度
結局
cos θ = (A と Bの内積 ) / (A.length * B.length)
これをユーザーAをログインユーザー、Bを残りユーザー一人ずつにして類似度を（全ユーザー) - 1 回計算して、高い順に並べて10人おすすめする。
（ファーストビューでフォローすれば、また計算し直して10人おすすめ）

2017-03-17 03:28 UTC, t-vinn commented
@NaotoOta お手すきでレビューお願いします！（コンフリクト解消しました）

2017-03-18 06:31 UTC, NaotoOta commented on app/controllers/users/users_controller.rb
> +      @unfollowing_users = current_user.recommended_user_ids.map { |id| User.find(id) }
- 上のコメントアウトは？？
- あとモデルメソッドの名前と変数名が一致してないようにみえるけど？
- `User.where(id: current_user.recommended_user_ids)`やな、クエリの数が全然変わってくる

2017-03-18 06:53 UTC, t-vinn commented on app/controllers/users/users_controller.rb
> +      @unfollowing_users = current_user.recommended_user_ids.map { |id| User.find(id) }
- 6行目のコメントアウトは最初これでもアリかと思って書きました
- @unfollowing_usersはやめたほうがいいですね。@recommended_user_idsとか
- whereも考えたのですが、whereだとidが小さい順に並んでしまうんですよね。レコメンドは1~10位マsまで並べてて、この順番を崩さないためにこうしました。

2017-03-19 07:49 UTC, t-vinn commented
変数名がモデルメソッドに対応してなかったのを直しました

2017-03-21 03:28 UTC, t-vinn commented
@NaotoOta ここって、小林さんレビューがいるんでしたっけ？一応修正済みです

2017-03-25 05:50 UTC, t-vinn commented
@NaotoOta お手すきでレビューお願いします

2017-03-27 00:36 UTC, NaotoOta requested changes

2017-03-27 00:36 UTC, NaotoOta commented on app/controllers/users/users_controller.rb
> +      @recommended_users = current_user.recommended_user_ids.map { |id| User.find(id) }
User.where(id: current_user.recommended_user_ids)

2017-03-27 02:20 UTC, t-vinn commented on app/controllers/users/users_controller.rb
> +      @recommended_users = current_user.recommended_user_ids.map { |id| User.find(id) }
where使ってからorderするってことですね。

2017-03-27 04:45 UTC, t-vinn commented on app/controllers/users/users_controller.rb
> +      @recommended_users = current_user.recommended_user_ids.map { |id| User.find(id) }
この部分はrecommend_modfiyで直したのですが、こういう場合、いったんこれはこれとしてmergeしていただいてもいいんでしょうか。あとでコンフリクト起こしに行ってるようなものですが。。

2017-03-27 04:46 UTC, NaotoOta commented on app/controllers/users/users_controller.rb
> +      @recommended_users = current_user.recommended_user_ids.map { |id| User.find(id) }
okいいよ笑

2017-03-27 08:55 UTC, t-vinn commented
@NaotoOta 修正しました

2017-03-27 23:40 UTC, NaotoOta approved these changes

2017-03-27 23:41 UTC, NaotoOta commented
@t-vinn 
@knao124 ご確認ください

2017-03-28 01:24 UTC, merged