Devise
t-vinn/faceHook pull request #3
Opened 2017-02-03 03:09 UTC by t-vinn

工数の1. ユーザーモデル関連(devise)
deviseのデフォルト設定をいじったのは、nameで登録できるのと、プロフィール変更でnameとかbirth_dateを追加・変更できる点(hobby(, 写真)は後回し)
ログイン時はnameは不要で、emailとpassword

2017-02-03 07:21 UTC, NaotoOta requested changes
基本的に使わないものは作らない

2017-02-03 07:21 UTC, NaotoOta commented on app/assets/javascripts/users.coffee
> +# You can use CoffeeScript in this file: http://coffeescript.org/
使わないなら消す

2017-02-03 07:21 UTC, NaotoOta commented on app/assets/stylesheets/users.scss
> +// You can use Sass (SCSS) here: http://sass-lang.com/
使わないなら消す

2017-02-03 07:21 UTC, NaotoOta commented on app/controllers/application_controller.rb
> +  before_action :authenticate_user!
admin作るならこれじゃできひんよね

2017-02-03 07:21 UTC, NaotoOta commented on app/controllers/application_controller.rb
> +  end
これって何？

2017-02-03 07:21 UTC, NaotoOta commented on app/helpers/users_helper.rb
> +end
使わないなら消す

2017-02-03 07:21 UTC, NaotoOta commented on app/views/devise/confirmations/new.html.slim
> += render "devise/shared/links"
これってデフォルトのままか

2017-02-03 07:21 UTC, NaotoOta commented on app/views/devise/mailer/confirmation_instructions.html.slim
> +  = link_to 'Confirm my account', confirmation_url(@resource, confirmation_token: @token)
このview使う？

2017-02-03 07:21 UTC, NaotoOta commented on app/views/devise/mailer/password_change.html.slim
> +  | We're contacting you to notify you that your password has been changed.
このview使う？

2017-02-03 07:21 UTC, NaotoOta commented on app/views/devise/mailer/reset_password_instructions.html.slim
> +  | Your password won't change until you access the link above and create a new one.
このview使う？

2017-02-03 07:21 UTC, NaotoOta commented on app/views/devise/mailer/unlock_instructions.html.slim
> +  = link_to 'Unlock my account', unlock_url(@resource, unlock_token: @token)
このview使う？

2017-02-03 07:21 UTC, NaotoOta commented on app/views/layouts/application.html.slim
> +          = link_to 'ログイン', new_user_session_path
partial化

2017-02-03 07:21 UTC, NaotoOta commented on app/views/layouts/mailer.html.slim
> +    = yield
このview使う？

2017-02-03 07:21 UTC, NaotoOta commented on app/views/layouts/mailer.text.slim
> += yield
このview使う？

2017-02-03 07:21 UTC, NaotoOta commented on test/controllers/users_controller_test.rb
> +require 'test_helper'
testはrspecで

2017-02-03 07:21 UTC, NaotoOta commented on test/fixtures/users.yml
> +# Read about fixtures at http://api.rubyonrails.org/classes/ActiveRecord/FixtureSet.html
testはrspecで

2017-02-03 07:21 UTC, NaotoOta commented on test/models/user_test.rb
> +require 'test_helper'
testはrspecで

2017-02-03 08:11 UTC, t-vinn commented on app/controllers/application_controller.rb
> +  before_action :authenticate_user!
これだとuserにログインしないとadmin機能も使えなくなっちゃうのでDevise::RegistrationsControllerみたいなの作ってそこに書かないといけないですかね

2017-02-03 08:13 UTC, t-vinn commented on app/controllers/application_controller.rb
> +  end
>これって何？
rails4 でstrong parametersが導入されたのでこのコードを書いとかないといけないという話で
http://ruby-rails.hatenadiary.com/entry/20140804/1407168000#devise-add-column-to-model

2017-02-03 08:15 UTC, t-vinn commented on app/views/devise/confirmations/new.html.slim
> += render "devise/shared/links"
デフォルトのままですね。ただconfirmation email使ってないので消して良いかもしれません

>これってデフォルトのままか

2017-02-03 08:24 UTC, NaotoOta commented on app/controllers/application_controller.rb
> +  before_action :authenticate_user!
まあこれは今後知ってもらえたら良いんやけど
Users::BaseControllerってのを作ってそこにUsers::BaseController < ApplicationControllerと書く
name_space :users 以下のcontrollerではHogeController < Users::BaseControllerとする

2017-02-03 08:26 UTC, NaotoOta commented on app/controllers/application_controller.rb
> +  end
へ〜〜〜なるほど

2017-02-03 08:27 UTC, NaotoOta commented on app/views/devise/confirmations/new.html.slim
> += render "devise/shared/links"
任せるけど
ある程度はviewも整えてもらうから
・都度やる
・あとでまとめてやる
好きな方選んでもらえれば

2017-02-03 08:40 UTC, t-vinn commented on app/views/devise/confirmations/new.html.slim
> += render "devise/shared/links"
そもそもサインアップ時にemailでリンク送ってそこからconfirmationすることは考えてなかったので、このviewに関しては消そうかと思ってます。view整えるのはあとでまとめてやろうと思ってます

2017-02-05 00:51 UTC, NaotoOta commented
@t-vinn ちなみに確認やけど自分で動作確認ってしてるよな？

2017-02-05 00:51 UTC, NaotoOta approved these changes

2017-02-05 01:16 UTC, merged