Recommend modify
t-vinn/faceHook pull request #30
Opened 2017-03-22 06:42 UTC by t-vinn

- Similaritiesテーブル、Similarities_usersテーブル
- rake task
①recommend: start_from_scratch
  既存のユーザーとフォロー関係より、similaritiesテーブルを一から構築する（createで入れる）
②recommend: daily_update
  毎日午前3時に、その前日にできたフォロー関係を元にsimilaritiesテーブルの値を書き換える（新たにフォローしたorされた人が関わるところだけ書き換える）
- user.rbのrecommended_user_idsは、similarityの高い順に並べる
- 新規ユーザーなどでフォロー関係がなく、類似度計算しても0になる場合は、フォロワーが多い人から順に10人オススメする

2017-03-23 05:13 UTC, t-vinn commented
rake task、新規ユーザーが無視される仕様になってたので修正中

2017-03-27 00:12 UTC, NaotoOta requested changes
みた

2017-03-27 00:12 UTC, NaotoOta commented on app/controllers/users/users_controller.rb
> +      @unfollowing_users = current_user.recommended_user_ids.first(10).map { |id| User.find(id) }
`User.where(id: current_user.recommended_user_ids.first(10))`
でorderで頑張るほうが圧倒的に軽そう

2017-03-27 00:12 UTC, NaotoOta commented on app/helpers/application_helper.rb
> +    if @unfollowing_users.present?
@はhelper内ではつかわない
引数にする

2017-03-27 00:12 UTC, NaotoOta commented on app/models/user.rb
> +                                     .where.not(user_id: id).pluck(:user_id)
これってなんで自分もSimilartiesUserにいうるん？

2017-03-27 00:12 UTC, NaotoOta commented on app/models/user.rb
> +    top_user_ids - FollowRelationship.where(follower_user_id: id).pluck(:followee_user_id)
これしてたら上のん意味なくない？

2017-03-27 00:12 UTC, NaotoOta commented on lib/tasks/recommend.rake
> +  end
serviceにしよう

2017-03-27 02:04 UTC, t-vinn commented on app/controllers/users/users_controller.rb
> +      @unfollowing_users = current_user.recommended_user_ids.first(10).map { |id| User.find(id) }
whereで一旦順番崩してからorderですね。
レコメンドロジックの中で一度ユーザーIDを類似度順に並べてるので、単純に同じことをまたやる感じにはなりますが、mapの重さを理解してませんでした。
current user 関連のsimilarity ID
first10関連の similarity ID
の重なり取ってきて類似度順に並べて、、とやってみます

2017-03-27 02:09 UTC, t-vinn commented on app/models/user.rb
> +                                     .where.not(user_id: id).pluck(:user_id)
User2人の組に対してそれぞれsimilarityが計算されるので、例えばユーザー30人でカレントユーザーがid 30だったら、
1 と 30、2 と30、...、29と30
のsimilarity があって、similarity userには
similarityID , user_id
の組で上の29通りの組に対してユーザー二人分で計58レコード入ってる感じです

2017-03-27 02:14 UTC, t-vinn commented on app/models/user.rb
> +    top_user_ids - FollowRelationship.where(follower_user_id: id).pluck(:followee_user_id)
登録したばかりのユーザーはフォロー誰もしてないので類似度が全てゼロで意味がない(top_ten計算しても、類似度以外のパラメータでソートすることになる)ので、こっちで書き換えてます

2017-03-27 02:39 UTC, t-vinn commented on app/models/user.rb
> +    top_user_ids - FollowRelationship.where(follower_user_id: id).pluck(:followee_user_id)
僕も見間違えそうになりました。top-user_ids マイナス　followrelationshipsですね。
top_user_idsだけだと全てのユーザーを類似度順に並び替えてるだけなのですが、それだと既にフォローしてるユーザーもオススメされちゃうので、フォロー済みの人を除く作業です。
コメントつけました

2017-03-27 02:41 UTC, t-vinn commented on app/helpers/application_helper.rb
> +    if @unfollowing_users.present?
修正しました

2017-03-27 02:49 UTC, t-vinn commented on app/controllers/users/users_controller.rb
> +      @unfollowing_users = current_user.recommended_user_ids.first(10).map { |id| User.find(id) }
少しトライしました。が、かえって大変な気がしました。
①フォローまだしてない場合などは、レコメンドをフォロー関係から決定しているのに対し、通常は類似度から決定している
②①のために、一旦whereで順番をバラしてから直そうとする時、並べ方が2通りあり、そのどちらが当てはまるかを決めて、、、となって、モデルでユーザー全員に対してやったのと全く同じ作業を10人に対して一からやり直す感じになってしまいます。。

2017-03-27 03:08 UTC, NaotoOta commented on app/models/user.rb
> +                                     .where.not(user_id: id).pluck(:user_id)
??
よくわかってないのでちょっと口頭で説明してほしい

2017-03-27 03:13 UTC, NaotoOta commented on app/controllers/users/users_controller.rb
> +      @unfollowing_users = current_user.recommended_user_ids.first(10).map { |id| User.find(id) }
```
ids = current_user.recommended_user_ids.first(10)
users = User.where(ids).index_by(&:id)
@unfollowing_users = ids.map { |id| users[id] } 
```

とかは？

2017-03-27 03:14 UTC, NaotoOta commented on app/models/user.rb
> +    top_user_ids - FollowRelationship.where(follower_user_id: id).pluck(:followee_user_id)
ああ、何を返してるのかが見づらいのか

2017-03-27 03:14 UTC, t-vinn commented on lib/tasks/recommend.rake
> +  end
しました！

2017-03-27 03:15 UTC, t-vinn commented
where.orderの部分以外修正しました！

2017-03-27 03:17 UTC, t-vinn commented on app/models/user.rb
> +                                     .where.not(user_id: id).pluck(:user_id)
説明がわかりにくくて失礼しました。
SimilarityUsersテーブルとかsimiralitiesテーブルとかはカレントユーザーに対するものではなくてユーザー全員に対するもので、レコメンドするときはそのテーブルのうちカレントユーザーに関係するとこだけ取ってきてるイメージです

2017-03-27 03:40 UTC, t-vinn commented on app/controllers/users/users_controller.rb
> +      @unfollowing_users = current_user.recommended_user_ids.first(10).map { |id| User.find(id) }
0.6秒→0.4秒になりました。ありがとうございます。

2017-03-27 03:42 UTC, t-vinn commented
@NaotoOta クエリの部分含め修正しました

2017-03-27 04:04 UTC, NaotoOta commented on app/models/user.rb
> +                                     .where.not(user_id: id).pluck(:user_id)
口頭で解決

2017-03-27 04:05 UTC, NaotoOta approved these changes

2017-03-27 04:05 UTC, NaotoOta commented
@t-vinn LG
@knao124 確認お願いします

2017-03-27 07:58 UTC, knao124 approved these changes

2017-03-27 08:03 UTC, merged