imitates facebook
t-vinn/faceHook pull request #35
Opened 2017-03-23 09:28 UTC by t-vinn

facebookを真似した
www.facebook.com

before
<img width="1280" alt="screen shot 2017-03-23 at 17 11 26" src="https://cloud.githubusercontent.com/assets/15964061/24240863/6895bac6-0ff6-11e7-99e4-599ab0869e96.png">

after
<img width="1280" alt="screen shot 2017-03-23 at 18 23 48" src="https://cloud.githubusercontent.com/assets/15964061/24240900/80fb0c42-0ff6-11e7-8a1e-2aeeb4380570.png">

2017-03-27 00:23 UTC, NaotoOta requested changes

2017-03-27 00:23 UTC, NaotoOta commented on app/assets/stylesheets/_bootstrap_and_overrides.sass
> +  color: #fff
overrideに書くものじゃなさそう

2017-03-27 04:35 UTC, t-vinn commented on app/assets/stylesheets/_bootstrap_and_overrides.sass
> +  color: #fff
layout/_layout.sassに移してみます

2017-03-27 04:43 UTC, t-vinn commented
@NaotoOta
一応修正done です
bootstrapの元々の設定をいじる感じのやつはoverrideで、今回の文字色はちょっと違ったのでlayoutに入れました

2017-03-27 23:41 UTC, NaotoOta commented
見た目よくなったｗ

2017-03-27 23:45 UTC, NaotoOta commented
@t-vinn cssとかの規約って渡したっけ？
https://github.com/FiNCDeveloper/online_works/blob/master/app/assets/stylesheets/base/_base.sass
- こんな感じで色とかは一箇所にまとめる
- spaceは4の倍数にして $default_space * ◯ ってやる
- プロパティはABC順
- margin-topとかはつかわない（基本は左右・上下対称で）

2017-03-28 00:26 UTC, t-vinn commented
ありがとうございます。適用します

2017-03-28 00:55 UTC, t-vinn commented
@NaotoOta 
margin-top以外は修正しました。
marginの部分は現状うまく直せずです

2017-03-28 01:26 UTC, NaotoOta commented
これでOKなのでコンフリクトだけ頼む

2017-03-28 01:26 UTC, NaotoOta approved these changes

2017-03-28 01:29 UTC, merged