Follow
t-vinn/faceHook pull request #5
Opened 2017-02-06 07:02 UTC by t-vinn

2017-02-06 07:22 UTC, NaotoOta requested changes
controllerの中身はあとで

2017-02-06 07:22 UTC, NaotoOta commented on app/assets/javascripts/follow_relationships.coffee
> +# You can use CoffeeScript in this file: http://coffeescript.org/
使わんのは消す

2017-02-06 07:22 UTC, NaotoOta commented on app/assets/stylesheets/follow_relationships.scss
> +// You can use Sass (SCSS) here: http://sass-lang.com/
使わんのは消す

2017-02-06 07:22 UTC, NaotoOta commented on app/controllers/users/base_controller.rb
> -
この変更って前のPRでやってたよな？

2017-02-06 07:22 UTC, NaotoOta commented on app/helpers/follow_relationships_helper.rb
> +end
使わないなら消す

2017-02-06 07:22 UTC, NaotoOta commented on config/routes.rb
> +      resources :follow_relationships
後ろにmodule: :usersって足す

2017-02-06 07:22 UTC, NaotoOta commented on app/controllers/users/follow_relationships_controller.rb
> +class Users::FollowRelationshipsController < Users::BaseController
Users::Users::FollowRelationShipsControllerにする

2017-02-06 07:22 UTC, NaotoOta commented on config/routes.rb
> +    resources :users do
ちなみにこれを噛ましてる理由は？

2017-02-06 07:25 UTC, t-vinn commented on config/routes.rb
> +    resources :users do
namespaceのusers/modelのuser/modelのfollow_relationshipにしてますが、users(namespace)/follow_relationshipsでも確かに良いかもしれません

2017-02-06 07:26 UTC, NaotoOta commented on config/routes.rb
> +    resources :users do
違いは？

2017-02-06 07:27 UTC, t-vinn commented on app/controllers/users/base_controller.rb
> -
前のPRでやりました。今回消したのは不要なコードで、消し忘れてたのに後になって気づきました

2017-02-06 07:30 UTC, t-vinn commented on config/routes.rb
> +    resources :users do
user has_many follow_relationshipsなのでthread has_many commentsと同じノリでネストしてました(namespaceが十分わかってなかったかも）

2017-02-06 07:32 UTC, t-vinn commented on config/routes.rb
> +    resources :users do
違いをうまく説明できないですが、namespace userの中にある時点でadminとは分かれているし不要な感じがします。ちょっと調べます

2017-02-06 07:36 UTC, NaotoOta commented on app/controllers/users/base_controller.rb
> -
ok

2017-02-06 07:36 UTC, NaotoOta commented on app/controllers/users/base_controller.rb
> -
実プロジェクトでは別PRが望ましい

2017-02-06 07:39 UTC, t-vinn commented on app/controllers/users/base_controller.rb
> -
followのPRに関係ないもの入れないということですね

2017-02-06 07:47 UTC, t-vinn commented on config/routes.rb
> +    resources :users do
userとfollow_relationshipの関係はこのルーティングを書いた時点ではhas_manyとしていたのでネストしましたが、今は単なるhas_manyではない（has_many_throughではあるがそれともちょっと違う気がする）ので、ネスト一択という思考はまず間違いで、

2017-02-06 07:48 UTC, NaotoOta commented on config/routes.rb
> +    resources :users do
has_many云々とroutingは基本的に全く別物であると思ってほしい

2017-02-06 07:49 UTC, t-vinn commented on config/routes.rb
> +    resources :users do
user has_many :following_users, through: :active_relationships(follow_relationshipsと同じようなもの）などとなっているので、users/user/following_usersとかがあるとRESTですかね

2017-02-06 08:02 UTC, t-vinn commented on config/routes.rb
> +    resources :users do
上のは間違い
follow_relationshipはユーザーごとに異なるってことがURLからわかるようにするためにネスト？
users(namespace)/users/users:id/follow_relationshipsならわかるけどusers(namespace)/follow_relationshipsだとフォロー関係が個人ごとな感じがしない

2017-02-06 08:04 UTC, NaotoOta commented on config/routes.rb
> +    resources :users do
ここでいうuser_idはfollowerを想定してる？followeeを想定してる？

2017-02-06 08:06 UTC, t-vinn commented on config/routes.rb
> +      resources :follow_relationships
そうすればコントローラーの継承？関係はそのままだがURLがusers/usersにならないってことですよね
scope module: :users do
  resources :users
end
ってことですか

2017-02-06 08:08 UTC, t-vinn commented on config/routes.rb
> +    resources :users do
そもそもfacebookのような友達関係でなくツイッターのようなフォロー関係（非対称、フォロー断れない）を想定しているので、user_idはフォローする側、followerの想定です

2017-02-06 08:09 UTC, NaotoOta commented on config/routes.rb
> +      resources :follow_relationships
namespace :users do
  resources :users do
    resources :follow_relationships, module: :users

2017-02-06 08:10 UTC, NaotoOta commented on config/routes.rb
> +    resources :users do
であればresources :usersはいらないってなる
その理由がわかるようになってほしい

2017-02-06 08:15 UTC, t-vinn commented on config/routes.rb
> +      resources :follow_relationships
これだとコントローラーは
Users::Users::FollowRelationshipsController
urlは
users/follow_relationships  (最初のusersはnamespace)
ってことですか
resources :usersの存在価値がよくわからなくなってきました

2017-02-06 08:16 UTC, NaotoOta commented on config/routes.rb
> +      resources :follow_relationships
urlはusers/users/:user_id/follow_relationships

>resources :usersの存在価値がよくわからなくなってきました

これは上で議論してるよな、また全然別の話

2017-02-06 08:23 UTC, t-vinn commented on config/routes.rb
> +      resources :follow_relationships
基本がわかってないかもしれないので確認させてください。
```
namespace :users do
  resources :users do
    resources :follow_relationships, module: :users
```
っていうのは、調べたところ
```
namespace :users do
  resources :users do
    scope module: :users do
      resources :follow_relationships
```
と同じだという理解です。そして、このルーティングだとurlはusers/users/users/follow_relationships、コントローラはUsers::Users::FollowRelationshipsControllerになるって理解で良いでしょうか。

2017-02-06 08:24 UTC, NaotoOta commented on config/routes.rb
> +      resources :follow_relationships
urlはusers/users/follow_relationshipsやな
controllerはあってる
同じなのもあってる

2017-02-06 08:24 UTC, NaotoOta commented on config/routes.rb
> +      resources :follow_relationships
正しくは実際にやってみてもらったほうが正確やけど（笑）

2017-02-06 08:29 UTC, t-vinn commented on config/routes.rb
> +      resources :follow_relationships
やってみました 現状の
```
namespace :users do
  resources :users do
      resources :follow_relationships
```
だとurlはusers/users/follow_relationshipなんだからscope moduleつけてもurl変わらないはずですね

2017-02-06 08:30 UTC, NaotoOta commented on config/routes.rb
> +      resources :follow_relationships
そこというかcontrollerの指定かな変わってくるのは

2017-02-07 08:28 UTC, NaotoOta requested changes
悪くはない

2017-02-07 08:28 UTC, NaotoOta commented on app/controllers/users/users/follow_relationships_controller.rb
> +      def index; end
なにこれ？

2017-02-07 08:28 UTC, NaotoOta commented on app/controllers/users/users/follow_relationships_controller.rb
> +    class FollowRelationshipsController < BaseController
これってこれでUsers::BaseControllerを継承してるん？

2017-02-07 08:28 UTC, NaotoOta commented on app/models/follow_relationship.rb
> +  validate :cant_follow_yourself
カスタムvalidationの命名はむずいとこやけど、
validate感あったほうが良いからcheck_follow_oneselfとかかな

2017-02-07 08:28 UTC, NaotoOta commented on app/models/follow_relationship.rb
> +  def cant_follow_yourself
privateメソッドはインデントもう一個下げる（これはOWのルール）

2017-02-07 08:28 UTC, NaotoOta commented on app/views/users/users/index.html.slim
> +        td = link_to 'Follow', users_follow_relationships_path(:follow_relationship=>{:follower_user_id=>current_user.id, :followee_user_id=>unfollowing_user.id}), method: :create, data:{confirm: "Fo
これはなんか変
なにをしようとしてる？

2017-02-07 08:28 UTC, NaotoOta commented on app/views/users/users/index.html.slim
> +        td = link_to 'Unfollow', users_follow_relationship_path(current_user.active_relationships.find_by(followee_user_id: following_user.id)), method: :delete, data:{confirm: "Unfollow this person?
viewのなかでクエリ呼ばない。
けどこれの解消方法はたぶん学ばないとわからないから答え言うと

`@follow_relation_ships_index_by_followee_user_id = current_user.active_relationships.index_by(&:followee_user_id)`

ってのをcontrollerで定義して
viewでは

`link_to 'Unfollow', users_follow_relationship_path(@follow_relation_ships_index_by_followee_user_id[following_user.id]), ...`

ってやる。
それぞれのメソッドが何をしているか

今の書き方との違いは何か

は自分で調べといて

2017-02-07 08:28 UTC, NaotoOta commented on app/views/users/follow_relationships/new.html.slim
> += link_to 'Back', user_follow_relationships_path(current_user.id)
ぱっとみやけどこのファイル使ってる？

2017-02-07 08:28 UTC, NaotoOta commented on config/routes.rb
> +    resources :follow_relationships, module: :users
only: []
で絞ろう

2017-02-07 08:28 UTC, NaotoOta commented on app/controllers/users/users/follow_relationships_controller.rb
> +          params.require(:follow_relationship).permit(:follower_user_id, :followee_user_id)
これはprivateメソッド化

2017-02-07 08:28 UTC, NaotoOta commented on app/controllers/users/users/follow_relationships_controller.rb
> +      def new
このアクション使ってる

2017-02-07 08:35 UTC, t-vinn commented on app/views/users/follow_relationships/new.html.slim
> += link_to 'Back', user_follow_relationships_path(current_user.id)
使ってないですね。。

2017-02-07 08:40 UTC, t-vinn commented on app/models/follow_relationship.rb
> +  def cant_follow_yourself
rubocopでそれをやってinconsistentと言われたので、
# Method definitions after `private` or `protected` isolated calls need one
# extra level of indentation.
Style/IndentationConsistency:
  Enabled: true
  EnforcedStyle: rails
をrubocop.yml
に足します

2017-02-07 08:43 UTC, NaotoOta commented on app/models/follow_relationship.rb
> +  def cant_follow_yourself
まじか
すまん（笑）
頼むわ

2017-02-07 08:44 UTC, t-vinn commented on app/controllers/users/users/follow_relationships_controller.rb
> +      def new
index使ってないですね

2017-02-07 08:45 UTC, t-vinn commented on app/controllers/users/users/follow_relationships_controller.rb
> +      def new
newも使ってませんでした

2017-02-07 08:47 UTC, t-vinn commented on app/controllers/users/users/follow_relationships_controller.rb
> +    class FollowRelationshipsController < BaseController
<の後の書き方がよくわからなかったんですが、BaseControllerのところをUsers::BaseControllerと書くとClassのUsersを継承したBaseControllerになるのかエラーが出てこれだとうまく行ってます。

2017-02-07 08:49 UTC, t-vinn commented on app/controllers/users/users/follow_relationships_controller.rb
> +          params.require(:follow_relationship).permit(:follower_user_id, :followee_user_id)
確かにそうでした

2017-02-07 08:53 UTC, NaotoOta commented on app/controllers/users/users/follow_relationships_controller.rb
> +    class FollowRelationshipsController < BaseController
authenticate_user!は機能してた？
そこが機能してるなら問題はなさげ

2017-02-07 08:55 UTC, t-vinn commented on app/controllers/users/users/follow_relationships_controller.rb
> +    class FollowRelationshipsController < BaseController
ログアウトしてからrootを呼ぶとyou need to sign in になるので多分大丈夫かと

2017-02-07 08:56 UTC, NaotoOta commented on app/controllers/users/users/follow_relationships_controller.rb
> +    class FollowRelationshipsController < BaseController
じゃあOK
これでいけるんや勉強になるなあ

2017-02-07 08:57 UTC, NaotoOta commented on app/controllers/users/users/follow_relationships_controller.rb
> +        if @follow_relationship.save!
- rootに飛ばすなら@にしてインスタンス変数にする必要はない
- いきなりif FollowRelationship.create(follow_relatinoship_params)でもいけるはず

2017-02-07 08:58 UTC, NaotoOta commented on app/controllers/users/users/follow_relationships_controller.rb
> +        @follow_relationship = FollowRelationship.find(params[:id])
同じくインスタンス変数にする必要ない

2017-02-07 09:00 UTC, t-vinn commented on app/controllers/users/users/follow_relationships_controller.rb
> +        if @follow_relationship.save!
確かに@を挟む意味はないですね
ルート以外に飛ばす場合にlink_toの引数として@が必要なら現状のように一旦@挟むって理解でいいでしょうか

2017-02-07 09:01 UTC, NaotoOta commented on app/controllers/users/users/follow_relationships_controller.rb
> +        if @follow_relationship.save!
引数に@が必要な場合ってのはないはず

- オブジェクト指向
- 変数のスコープ

らへんがキーワードやけど、最終研修後でいい要件なのでもし暇があれば調べるといいけど
一旦はこっち作るのにフォーカスで

2017-02-07 09:08 UTC, t-vinn commented on app/views/users/users/index.html.slim
> +        td = link_to 'Follow', users_follow_relationships_path(:follow_relationship=>{:follower_user_id=>current_user.id, :followee_user_id=>unfollowing_user.id}), method: :create, data:{confirm: "Fo
createアクションの方にfollower_user_idと~ee_user_idを送ろうとしてました
が、コントローラでやればいいことですかね

2017-02-07 09:10 UTC, NaotoOta commented on app/views/users/users/index.html.slim
> +        td = link_to 'Follow', users_follow_relationships_path(:follow_relationship=>{:follower_user_id=>current_user.id, :followee_user_id=>unfollowing_user.id}), method: :create, data:{confirm: "Fo
- 両方送る必要ある？
- method: :createじゃなくても書けるはず

2017-02-07 09:13 UTC, t-vinn commented on app/views/users/users/index.html.slim
> +        td = link_to 'Unfollow', users_follow_relationship_path(current_user.active_relationships.find_by(followee_user_id: following_user.id)), method: :delete, data:{confirm: "Unfollow this person?
ありがとうございます。これでいけました。

2017-02-07 09:21 UTC, t-vinn commented on app/views/users/users/index.html.slim
> +        td = link_to 'Follow', users_follow_relationships_path(:follow_relationship=>{:follower_user_id=>current_user.id, :followee_user_id=>unfollowing_user.id}), method: :create, data:{confirm: "Fo
unfollowing userの方はviewから送らないといけないかと思いました。viewでeachと展開してるので
current_userの方はcontrollerの方でもいけるかもしれないです

2017-02-07 09:28 UTC, t-vinn commented on app/views/users/users/index.html.slim
> +        td = link_to 'Follow', users_follow_relationships_path(:follow_relationship=>{:follower_user_id=>current_user.id, :followee_user_id=>unfollowing_user.id}), method: :create, data:{confirm: "Fo
method: :createじゃないというのはaction: createとかの方が良いということですか？

2017-02-07 09:29 UTC, NaotoOta commented on app/views/users/users/index.html.slim
> +        td = link_to 'Follow', users_follow_relationships_path(:follow_relationship=>{:follower_user_id=>current_user.id, :followee_user_id=>unfollowing_user.id}), method: :create, data:{confirm: "Fo
method: :postで行ける気がする
createはmethodではない

2017-02-07 09:32 UTC, t-vinn commented on app/views/users/users/index.html.slim
> +        td = link_to 'Follow', users_follow_relationships_path(:follow_relationship=>{:follower_user_id=>current_user.id, :followee_user_id=>unfollowing_user.id}), method: :create, data:{confirm: "Fo
うーん確かにそうでした。createはHTTPメソッドじゃなくてコントローラーのアクションですね。
createでもいけてたのはrubyが優しかったんですかね

2017-02-07 09:48 UTC, t-vinn commented on app/views/users/users/index.html.slim
> +        td = link_to 'Follow', users_follow_relationships_path(:follow_relationship=>{:follower_user_id=>current_user.id, :followee_user_id=>unfollowing_user.id}), method: :create, data:{confirm: "Fo
これ書いた時は掲示板でフォームからcreateしたのからの類推でviewの方から送ってやらないとcontrollerでrequire().permit()した時にunknown attributeになると思ってました
そうじゃない方法もあると思うので少し調べます

2017-02-07 10:03 UTC, t-vinn commented on app/views/users/users/index.html.slim
> +        td = link_to 'Follow', users_follow_relationships_path(:follow_relationship=>{:follower_user_id=>current_user.id, :followee_user_id=>unfollowing_user.id}), method: :create, data:{confirm: "Fo
link_toでパラメーターを送りまくるのはあまり綺麗ではないので、form_forにした方がbetterでしょうか。partial化すればviewも若干見やすくなるような気はします。viewから送らない方法はよくわかりません

2017-02-07 14:30 UTC, NaotoOta requested changes
もうちょい

2017-02-07 14:30 UTC, NaotoOta commented on config/routes.rb
> +    resources :follow_relationships, module: :users, only: [:create, :destroy]
moduleとonlyの順番逆が自然やな

2017-02-07 14:30 UTC, NaotoOta commented on app/views/users/users/index.html.slim
> +        td = link_to 'Unfollow', users_follow_relationship_path(@follow_relationships_index_by_followee_user_id[following_user.id]), method: :delete, data:{confirm: "Unfollow this person?"}
さすがに長いから改行しよう

2017-02-07 14:30 UTC, NaotoOta commented on app/views/users/users/index.html.slim
> +        td = link_to 'Unfollow', users_follow_relationship_path(@follow_relationships_index_by_followee_user_id[following_user.id]), method: :delete, data:{confirm: "Unfollow this person?"}
あとrailsでは
- `:`のあとは一文字あける
- `{}`の中は両端一文字ずつあける

のが普通。
rubocopがviewに効いてないっぽいので調べるわ

2017-02-07 14:30 UTC, NaotoOta commented on app/views/users/users/index.html.slim
> +        td = link_to 'Follow', users_follow_relationships_path(:follow_relationship=>{:follower_user_id=>current_user.id, :followee_user_id=>unfollowing_user.id}), method: :post, data:{confirm: "Foll
あとはここだけやな

2017-02-08 03:53 UTC, NaotoOta commented on app/views/users/users/index.html.slim
> +        td = link_to 'Follow', users_follow_relationships_path(follow_relationship: { follower_user_id: current_user.id, followee_user_id: unfollowing_user.id }), method: :post, data: { confirm: "Fol
```
td = link_to 'Follow',
  users_follow_relationships_path(followee_user_id: unfollowing_user.id),
  method: :post,
  data: { confirm: 'Follow this person?' }
```

かな

2017-02-08 03:54 UTC, NaotoOta commented on app/views/users/users/index.html.slim
> +        td = link_to 'Unfollow', users_follow_relationship_path(@follow_relationships_index_by_followee_user_id[following_user.id]), method: :delete, data: { confirm: "Unfollow this person?" }
```
td = link_to 'Unfollow',
  users_follow_relationship_path(@follow_relationships_index_by_followee_user_id[following_user.id]),
  method: :delete,
  data: { confirm: 'Unfollow this person?' }
```

かな

2017-02-08 06:39 UTC, t-vinn commented on app/views/users/users/index.html.slim
> +        td = link_to 'Follow', users_follow_relationships_path(follow_relationship: { follower_user_id: current_user.id, followee_user_id: unfollowing_user.id }), method: :post, data: { confirm: "Fol
ありがとうございます。
こうして、コントローラの方でassign_attributes(hoge: hoge, hogem: hogem)みたいにしてsaveしたらstrong parametersに引っかかってunpermitted parametersになるのかと思っていましたが、どうも引っかからないようです。

2017-02-08 06:41 UTC, t-vinn commented on app/views/users/users/index.html.slim
> +        td = link_to 'Unfollow', users_follow_relationship_path(@follow_relationships_index_by_followee_user_id[following_user.id]), method: :delete, data: { confirm: "Unfollow this person?" }
ありがとうございます。slimは行単位が命なんですね。
```
if ( ) {
hogehoge
}
のノリでカッコの始まりで改行してはエラーを出していました。。

2017-02-08 06:42 UTC, NaotoOta commented
@t-vinn masterマージしといてね

2017-02-08 06:43 UTC, t-vinn commented
じゃないとslim-lintできないですね。

2017-02-08 06:55 UTC, t-vinn commented on app/views/users/users/index.html.slim
> +        td = link_to 'Unfollow', users_follow_relationship_path(@follow_relationships_index_by_followee_user_id[following_user.id]), method: :delete, data: { confirm: "Unfollow this person?" }
これでも長すぎるって出ますね。かっこは一行に収めたいけど。。

2017-02-08 06:56 UTC, t-vinn commented on app/views/users/users/index.html.slim
> +        td = link_to 'Follow', users_follow_relationships_path(follow_relationship: { follower_user_id: current_user.id, followee_user_id: unfollowing_user.id }), method: :post, data: { confirm: "Fol
こっちは82文字で弾かれてるので100文字にしてしまうか。。

2017-02-08 06:57 UTC, t-vinn commented on app/views/users/users/index.html.slim
> +        td = link_to 'Unfollow', users_follow_relationship_path(@follow_relationships_index_by_followee_user_id[following_user.id]), method: :delete, data: { confirm: "Unfollow this person?" }
110文字なので変数の名前を短くしますか

2017-02-08 06:57 UTC, NaotoOta commented on app/views/users/users/index.html.slim
> +        td = link_to 'Unfollow', users_follow_relationship_path(@follow_relationships_index_by_followee_user_id[following_user.id]), method: :delete, data: { confirm: "Unfollow this person?" }
やむなし
このファイルの一番上に行の長さのチェックenable falseにするやつ書こう

2017-02-08 07:40 UTC, NaotoOta commented on app/controllers/users/users/follow_relationships_controller.rb
> +        )
@いらんて(笑)

follow_relationship = current_user.follow_relationships.build(followee_user_id: params[:followee_user_id])

2017-02-10 03:09 UTC, merged